"""About & Ethics: methodology, data sources, limitations, model cards,
privacy policy, helplines and acknowledgements.
"""

from __future__ import annotations

import sys
from pathlib import Path

for _p in (Path(__file__).resolve().parents[1], Path(__file__).resolve().parents[2]):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import streamlit as st  # noqa: E402

from app.components import helplines, sidebar, theme  # noqa: E402
from mindsense import inference  # noqa: E402
from mindsense.utils.io import load_config, read_table, repo_path  # noqa: E402

st.set_page_config(page_title="About & Ethics — MindSense", page_icon="⚖️", layout="wide")
theme.apply()
sidebar.render_sidebar()

st.title("⚖️ About, Ethics & Limitations")

# --------------------------------------------------------------------------- #
st.subheader("What this project is")
st.markdown(
    """
MindSense is an academic mini-project: a mental-health **screening aid** that
combines a tabular risk model (lifestyle/survey data), validated screening
instruments (PHQ-9, GAD-7, DASS-42), text-based mental-state classifiers, and
an optional facial-expression cue.

**How it works, in one line each:**
1. **Data pipeline** — acquisition ladder → cleaning → harmonised schema → stratified 70/15/15 split (seed 42).
2. **EDA** — distributions and associations, never causal claims.
3. **Image cue** — small CNN on FER-2013 with Grad-CAM (off by default).
4. **Prognosis** — DASS severity bands + a compact 14-item screener.
5. **Entities** — rule+lexicon extraction of clinical-style mentions from text.
6. **Risk model** — calibrated tree model on the harmonised lifestyle features, with SHAP explanations.
7. **Text mining** — TF-IDF/logistic baseline and a transformer for mental-state statements.
8. **Explainability & fairness** — SHAP/LIME on examples; subgroup metrics per report.
"""
)

st.error(
    "**What this is NOT:** not a diagnostic tool, not a treatment recommender, "
    "not a crisis service, not a substitute for a qualified professional. "
    "Every model here is trained on observational survey/corpus data with known "
    "biases (self-selected online samples, English-only text, uneven demographic "
    "coverage). Scores describe questionnaire responses — they do not describe "
    "who you are.",
    icon="🚫",
)

# --------------------------------------------------------------------------- #
st.subheader("Data & sources")
inventory_path = repo_path("reports", "tables", "data_inventory.csv")
if inventory_path.exists():
    inv = read_table(inventory_path)
    cols = [c for c in ["key", "tier", "population", "rows", "licence",
                        "data_source", "access_status"] if c in inv.columns]
    st.dataframe(inv[cols], width="stretch", height=350)
else:
    st.info("Run `make data` to generate the data inventory.")

config = load_config()
st.caption(
    "Full ranked list with links: **Lab Results → Ranked datasets** · "
    "column definitions: `docs/DATA_DICTIONARY.md`. "
    "Row-level data is never committed (licences/ToS); only aggregates are."
)

# --------------------------------------------------------------------------- #
st.subheader("Model cards")
card_paths = sorted(repo_path("docs").glob("MODEL_CARD*.md")) if repo_path(
    "docs"
).exists() else []
if not card_paths:
    st.info(
        "Per-model cards are generated by the training runs into "
        "`docs/MODEL_CARD_*.md` (status, data, metrics, fairness, intended use). "
        "Nothing trained yet → run `make train`."
    )
for card in card_paths:
    with st.expander(card.stem.replace("_", " ").title()):
        st.markdown(card.read_text(encoding="utf-8"))

status = inference.availability()
st.caption(
    "Current artifact status: "
    + " · ".join(
        f"{info['label']}: {'ready' if info['available'] else 'missing'}"
        for info in status.values()
    )
)

# --------------------------------------------------------------------------- #
st.subheader("Privacy & data handling")
st.markdown(
    """
- **In-memory only.** Questionnaire answers, text and photos stay in this
  session's memory (Streamlit `session_state`). Nothing is uploaded to a server
  or written to disk by the app.
- **No accounts, no tracking, no cookies** beyond the session itself. Close the
  tab and the data is gone.
- **Photos are never saved.** The face module processes bytes in memory; the
  image is discarded after inference.
- **No row-level data in git.** `data/raw/` and `data/processed/` are
  git-ignored; only aggregate reports are committed (DECISIONS #13).
- **Helplines** in `config/helplines.yaml` are public service numbers, verified
  on 2026-10-08.
"""
)

# --------------------------------------------------------------------------- #
st.subheader("Helplines (your selected region)")
helplines.render_lines()
st.caption("Change the region in the sidebar. This page never calls anyone for you.")

# --------------------------------------------------------------------------- #
st.subheader("Known limitations")
st.markdown(
    """
1. **Self-selection bias** — the DASS-42 and OSMI samples are people who chose
   to take an online test; group rates are not population prevalence.
2. **Label noise** — sentiment labels are corpus annotations, not clinician
   diagnoses; the 7-class corpus overlaps 2 819 posts with Dreaddit
   (quantified in `reports/tables/text_leakage_report.json`).
3. **Demographic coverage** — gender beyond male/female/other and non-English
   texts are under-represented; fairness tables (Exp 8) show where errors are
   uneven.
4. **Associations only** — the what-if sliders move a model's input, not a
   causal world; no interventional claims are made anywhere in the app.
5. **No personal longitudinal data** — the mood tracker is session-only by
   design; we do not collect or store histories.
6. **Regulatory** — this is not a medical device and makes no CE/FDA-style
   claims; it must not be deployed for clinical or insurance decisions.
"""
)

# --------------------------------------------------------------------------- #
st.subheader("Ethical use statement")
st.markdown(
    """
Use MindSense as a **conversation starter** with a human being — a counsellor,
doctor, or someone you trust. If you are in distress, use the helplines above
**now**; the app's crisis banner will surface them whenever PHQ-9 item 9 or a
crisis phrase is detected.

Do **not** use it to screen other people without consent, to make hiring/
academic/insurance decisions, or to delay seeking professional help.
"""
)

# --------------------------------------------------------------------------- #
st.subheader("Acknowledgements & references")
st.markdown(
    """
- **Instruments**: PHQ-9 (Kroenke, Spitzer & Williams, 2001), GAD-7
  (Spitzer et al., 2006), DASS-42 (Lovibond & Lovibond, 1995; official items
  from UNSW, public domain), GAD-2, WHO-5.
- **Datasets**: listed with licences in Lab Results → Ranked datasets
  (Kaggle/Opendatasoft/OpenPsychometrics/Dreaddit/Drugs.com/FER-2013 …).
- **Libraries**: scikit-learn, XGBoost, PyTorch, transformers, SHAP, LIME,
  Plotly, Streamlit — see `requirements.txt` / `requirements-train.txt`.
- Course: Honors Mini-Project, 2026.
"""
)

st.divider()
st.caption(
    "Decision log (every deviation, rationale): docs/DECISIONS.md · "
    "spec: prompt.md"
)
